var res = {
    HelloWorld_png : "res/HelloWorld.png",
    rabbitDown:"res/rabbitDown.png",
    rabbitJump:"res/rabbitJump.png",
    rabbitWalk:"res/rabbitWalk.png",
    radish:"res/radish.png",
    grassBackground:"res/grassBackground.png",
    colorBackground:"res/background.jpg",
    cave:"res/cave.png",
    jumpBackground:"res/jumpBackground.png",
    board:"res/board.png",
    puzzleBackground:"res/puzzleBackground.png",
    f1:"res/first/f1.png",
    f2:"res/first/f2.png",
    f3:"res/first/f3.png",
    f4:"res/first/f4.png",
    f5:"res/first/f5.png",
    fAnswer:"res/first/fAnswer.jpg",
    s1:"res/second/s1.png",
    s2:"res/second/s2.png",
    s3:"res/second/s3.png",
    s4:"res/second/s4.png",
    s5:"res/second/s5.png",
    s6:"res/second/s6.png",
    s7:"res/second/s7.png",
    sAnswer:"res/second/sAnswer.png",
    t1:"res/third/t1.png",
    t2:"res/third/t2.png",
    t3:"res/third/t3.png",
    t4:"res/third/t4.png",
    t5:"res/third/t5.png",
    t6:"res/third/t6.png",
    t7:"res/third/t7.png",
    tAnswer:"res/third/tAnswer.jpg",
    waterBackground:"res/waterBackground.jpg",
    pipeArc:"res/tube/pipeArc.png",
    pipeCircle:"res/tube/pipeCircle.png",
    pipeLine:"res/tube/pipeLine.png",
    pipeNode:"res/tube/pipeNode.png",
    backHome:"res/backHome.png",
    eatRadishSelection:"res/eatRadishSelection.png",
    jumpSelection:"res/JumpSelection.png",
    menu:"res/menu.png",
    puzzleSelection:"res/PuzzleSelection.png",
    tubeSelection:"res/tubeSelection.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
